import type { PermissionActionId } from "./permissions.js";
import type { PermissionRoleLabel } from "./types.js";

export const PERMISSION_ACTIONS: Array<{ id: PermissionActionId; group: string; label: string }> = [
  { id: "tasks.create", group: "Tasks", label: "Create tasks" },
  { id: "tasks.edit", group: "Tasks", label: "Edit task details (title, priority, due date, owners)" },
  { id: "tasks.move", group: "Tasks", label: "Move tasks between statuses (drag/drop)" },
  { id: "tasks.delete", group: "Tasks", label: "Delete tasks (send to Trash)" },
  { id: "tasks.addUpdate", group: "Tasks", label: "Post task updates" },
  { id: "trash.restore", group: "Trash", label: "Restore deleted tasks" },
  { id: "projects.create", group: "Projects", label: "Create projects" },
  { id: "projects.rename", group: "Projects", label: "Rename projects" },
  { id: "projects.delete", group: "Projects", label: "Delete projects" },
  { id: "projects.manageMembers", group: "Projects", label: "Manage project membership" },
  { id: "teams.create", group: "Teams", label: "Create teams" },
  { id: "teams.rename", group: "Teams", label: "Rename teams" },
  { id: "teams.delete", group: "Teams", label: "Delete teams" },
  { id: "teams.manageMembers", group: "Teams", label: "Manage team membership" },
  { id: "staff.create", group: "Team Members", label: "Add team members" },
  { id: "staff.edit", group: "Team Members", label: "Edit team member name/job title" },
  { id: "staff.delete", group: "Team Members", label: "Remove team members" },
  { id: "staff.assignRole", group: "Team Members", label: "Assign permission role to a team member" },
  { id: "schedule.create", group: "Schedule", label: "Create schedule events" },
  { id: "schedule.edit", group: "Schedule", label: "Edit, move, or resize schedule events" },
  { id: "schedule.delete", group: "Schedule", label: "Delete schedule events" },
  { id: "backup.export", group: "Backup", label: "Export a backup file" },
  { id: "backup.import", group: "Backup", label: "Import a backup file" },
  { id: "settings.editPermissions", group: "Settings", label: "Edit the permission matrix" }
];

export const DEFAULT_PERMISSION_MATRIX: Record<PermissionRoleLabel, Record<string, boolean>> = {
  "Super Admin": Object.fromEntries(PERMISSION_ACTIONS.map((a) => [a.id, true])),
  Admin: {
    "tasks.create": true,
    "tasks.edit": true,
    "tasks.move": true,
    "tasks.delete": true,
    "tasks.addUpdate": true,
    "trash.restore": true,
    "projects.create": true,
    "projects.rename": true,
    "projects.delete": true,
    "projects.manageMembers": true,
    "teams.create": true,
    "teams.rename": true,
    "teams.delete": true,
    "teams.manageMembers": true,
    "staff.create": true,
    "staff.edit": true,
    "staff.delete": true,
    "staff.assignRole": true,
    "schedule.create": true,
    "schedule.edit": true,
    "schedule.delete": true,
    "backup.export": true,
    "backup.import": true,
    "settings.editPermissions": true
  },
  Lead: {
    "tasks.create": true,
    "tasks.edit": true,
    "tasks.move": true,
    "tasks.delete": true,
    "tasks.addUpdate": true,
    "trash.restore": true,
    "projects.create": false,
    "projects.rename": false,
    "projects.delete": false,
    "projects.manageMembers": true,
    "teams.create": false,
    "teams.rename": false,
    "teams.delete": false,
    "teams.manageMembers": true,
    "staff.create": false,
    "staff.edit": false,
    "staff.delete": false,
    "staff.assignRole": false,
    "schedule.create": true,
    "schedule.edit": true,
    "schedule.delete": true,
    "backup.export": true,
    "backup.import": false,
    "settings.editPermissions": false
  },
  "Senior Staff": {
    "tasks.create": true,
    "tasks.edit": true,
    "tasks.move": true,
    "tasks.delete": false,
    "tasks.addUpdate": true,
    "trash.restore": false,
    "projects.create": false,
    "projects.rename": false,
    "projects.delete": false,
    "projects.manageMembers": false,
    "teams.create": false,
    "teams.rename": false,
    "teams.delete": false,
    "teams.manageMembers": false,
    "staff.create": false,
    "staff.edit": false,
    "staff.delete": false,
    "staff.assignRole": false,
    "schedule.create": true,
    "schedule.edit": true,
    "schedule.delete": false,
    "backup.export": true,
    "backup.import": false,
    "settings.editPermissions": false
  },
  "Junior Staff": {
    "tasks.create": false,
    "tasks.edit": false,
    "tasks.move": true,
    "tasks.delete": false,
    "tasks.addUpdate": true,
    "trash.restore": false,
    "projects.create": false,
    "projects.rename": false,
    "projects.delete": false,
    "projects.manageMembers": false,
    "teams.create": false,
    "teams.rename": false,
    "teams.delete": false,
    "teams.manageMembers": false,
    "staff.create": false,
    "staff.edit": false,
    "staff.delete": false,
    "staff.assignRole": false,
    "schedule.create": false,
    "schedule.edit": false,
    "schedule.delete": false,
    "backup.export": false,
    "backup.import": false,
    "settings.editPermissions": false
  }
};
