import express from "express";
import cors from "cors";
import helmet from "helmet";
import rateLimit from "express-rate-limit";
import pinoHttp from "pino-http";
import { env } from "./config/env.js";
import { logger } from "./config/logger.js";
import { requestId } from "./middleware/request-id.js";
import { errorHandler } from "./middleware/error-handler.js";
import { authRouter } from "./modules/auth/auth.routes.js";
import { employeeAdminRouter } from "./modules/employees/employee.routes.js";
import { officeAdminRouter } from "./modules/offices/office.routes.js";
import { scheduleAdminRouter } from "./modules/schedules/schedule.routes.js";
import { attendanceRouter } from "./modules/attendance/attendance.routes.js";

export const app = express();
app.disable("x-powered-by");
app.use(requestId);
app.use(pinoHttp({ logger }));
app.use(helmet());
app.use(cors({ origin: env.CORS_ORIGINS.split(","), credentials: true }));
app.use(express.json({ limit: "1mb" }));
app.use(rateLimit({ windowMs: 60_000, limit: 120, standardHeaders: true, legacyHeaders: false }));
app.get("/api/v1/health", (_req,res)=>res.json({status:"ok",timestamp:new Date().toISOString()}));
app.use("/api/v1/auth", authRouter);
app.use("/api/v1/admin/employees", employeeAdminRouter);
app.use("/api/v1/admin/offices", officeAdminRouter);
app.use("/api/v1/admin/schedules", scheduleAdminRouter);
app.use("/api/v1/attendance", attendanceRouter);
app.use((_req,res)=>res.status(404).json({error:{code:"NOT_FOUND",message:"Route not found"}}));
app.use(errorHandler);
